# Generated by Django 3.2.6 on 2022-09-16 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='accounts.Category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_creator', to='accounts.account')),
                ('parties', models.ManyToManyField(related_name='dispute_parties', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField()),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dispute')),
                ('mediator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mediator')),
                ('parties', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('file_name', models.CharField(blank=True, max_length=320, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('file_size', models.CharField(blank=True, max_length=10, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
            ],
        ),
    ]
